import Head from "next/head";

const Meta = () => {
  return (
    <Head>
      <title>Hacking Transitions</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
export default Meta;
