import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "./Header/Header";
import Footer from "./Footer";

//=========================  LOGIN PAGE ==================
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Footer />
    </div>
  );
}
